# Generated by Django 5.2.1 on 2025-05-10 20:35

from django.db import migrations


def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "The A team",
        "bravo": "The B team",
        "charlie": "The C team"
    }
    Team = apps.get_model ("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250510_2035'),
    ]

    operations = [
        migrations.RunPython(populate_team)
    ]
